CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      name VARCHAR(255) NOT NULL,
      email VARCHAR(512) NOT NULL,
      CONSTRAINT pk_user PRIMARY KEY (id),
      CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      name VARCHAR(255) NOT NULL,
      description VARCHAR(1000) NOT NULL,
      is_available BOOLEAN,
      request_id BIGINT,
      owner_id BIGINT  NOT NULL,
      CONSTRAINT pk_item PRIMARY KEY (id)

);

CREATE TABLE IF NOT EXISTS bookings (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      start_date TIMESTAMP WITHOUT TIME ZONE not null,
      end_date TIMESTAMP WITHOUT TIME ZONE not null,
      item_id  BIGINT,
      booker_id BIGINT,
      status VARCHAR not null ,
      CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      description VARCHAR(1000) NOT NULL,
      requestor_id BIGINT,
      CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      text VARCHAR(1000) NOT NULL,
      item_id BIGINT,
      author_id BIGINT,
      CONSTRAINT pk_comment PRIMARY KEY (id)
);




